import './bootstrap';
import './date-input-locale';
import './image-upload-compress';
import './bulk-unit-ranges';
import './qr-pack-download';
import './promo-tracking';
import './promo-campaign-editor';
import './welcome-text-reveal';
import './reservation-default-window';
