<?php

return [
    'trial_days' => (int) env('BILLING_TRIAL_DAYS', 30),
    'trial_plan_facility' => 'trial',
    'paid_expiry_grace_days' => (int) env('BILLING_PAID_GRACE_DAYS', 7),
    'allow_tenant_self_activation' => (bool) env('BILLING_ALLOW_SELF_ACTIVATION', true),
    'subscription_period_days' => (int) env('BILLING_SUBSCRIPTION_PERIOD_DAYS', 30),
    'contact_email' => env('BILLING_CONTACT_EMAIL', 'info@winprox.app'),

    'api_rate_limits' => [
        'trial' => ['max_attempts' => 30, 'decay_seconds' => 60],
        'time' => ['max_attempts' => 60, 'decay_seconds' => 60],
        'facility' => ['max_attempts' => 200, 'decay_seconds' => 60],
        'corporate' => ['max_attempts' => 10000, 'decay_seconds' => 60],
    ],

    'trial' => [
        'units_limit' => 10,
        'users_limit' => 2,
        'documents_org_limit' => 10,
        'photos_org_limit' => 10,
        'documents_per_unit' => null,
        'announcements_per_unit' => null,
        'includes_facility' => true,
        'time_module' => true,
        'esg_module' => false,
        'api_access' => false,
        'csv_workers_import' => true,
        'csv_units_import' => true,
    ],

    'plans' => [
        'time' => [
            'label_key' => 'subscription.plans.time.name',
            'units_limit' => 10,
            'users_limit' => 2,
            'documents_org_limit' => 10,
            'photos_org_limit' => 10,
            'documents_per_unit' => null,
            'announcements_per_unit' => null,
            'includes_facility' => false,
            'time_module' => true,
            'esg_module' => false,
            'api_access' => false,
            'csv_workers_import' => true,
            'csv_units_import' => false,
            'subscription_period_days' => 30,
            'self_activate' => true,
        ],
        'facility' => [
            'label_key' => 'subscription.plans.facility.name',
            'units_limit' => 100,
            'users_limit' => 5,
            'documents_org_limit' => 100,
            'photos_org_limit' => 100,
            'documents_per_unit' => null,
            'announcements_per_unit' => null,
            'includes_facility' => true,
            'time_module' => true,
            'esg_module' => false,
            'api_access' => false,
            'csv_workers_import' => true,
            'csv_units_import' => true,
            'subscription_period_days' => 30,
            'self_activate' => true,
        ],
        'corporate' => [
            'label_key' => 'subscription.plans.corporate.name',
            'units_limit' => null,
            'users_limit' => null,
            'documents_org_limit' => null,
            'photos_org_limit' => null,
            'documents_per_unit' => null,
            'announcements_per_unit' => null,
            'includes_facility' => true,
            'time_module' => true,
            'esg_module' => true,
            'api_access' => true,
            'csv_workers_import' => true,
            'csv_units_import' => true,
            'subscription_period_days' => 30,
            'self_activate' => true,
        ],
    ],
];
