<?php

return array (
  0 => 
  array (
    'code' => 'BE',
    'name_nl' => 'België',
    'name_en' => 'Belgium',
    'name_fr' => 'Belgique',
    'name_de' => 'Belgien',
    'name_es' => 'Bélgica',
    'name_it' => 'Belgio',
    'sort_order' => 10,
  ),
  1 => 
  array (
    'code' => 'NL',
    'name_nl' => 'Nederland',
    'name_en' => 'Netherlands',
    'name_fr' => 'Pays-Bas',
    'name_de' => 'Niederlande',
    'name_es' => 'Países Bajos',
    'name_it' => 'Paesi Bassi',
    'sort_order' => 20,
  ),
  2 => 
  array (
    'code' => 'FR',
    'name_nl' => 'Frankrijk',
    'name_en' => 'France',
    'name_fr' => 'France',
    'name_de' => 'Frankreich',
    'name_es' => 'Francia',
    'name_it' => 'Francia',
    'sort_order' => 30,
  ),
  3 => 
  array (
    'code' => 'DE',
    'name_nl' => 'Duitsland',
    'name_en' => 'Germany',
    'name_fr' => 'Allemagne',
    'name_de' => 'Deutschland',
    'name_es' => 'Alemania',
    'name_it' => 'Germania',
    'sort_order' => 40,
  ),
  4 => 
  array (
    'code' => 'LU',
    'name_nl' => 'Luxemburg',
    'name_en' => 'Luxembourg',
    'name_fr' => 'Luxembourg',
    'name_de' => 'Luxemburg',
    'name_es' => 'Luxemburgo',
    'name_it' => 'Lussemburgo',
    'sort_order' => 50,
  ),
  5 => 
  array (
    'code' => 'GB',
    'name_nl' => 'Verenigd Koninkrijk',
    'name_en' => 'United Kingdom',
    'name_fr' => 'Royaume-Uni',
    'name_de' => 'Vereinigtes Königreich',
    'name_es' => 'Reino Unido',
    'name_it' => 'Regno Unito',
    'sort_order' => 60,
  ),
  6 => 
  array (
    'code' => 'IE',
    'name_nl' => 'Ierland',
    'name_en' => 'Ireland',
    'name_fr' => 'Irlande',
    'name_de' => 'Irland',
    'name_es' => 'Irlanda',
    'name_it' => 'Irlanda',
    'sort_order' => 70,
  ),
  7 => 
  array (
    'code' => 'ES',
    'name_nl' => 'Spanje',
    'name_en' => 'Spain',
    'name_fr' => 'Espagne',
    'name_de' => 'Spanien',
    'name_es' => 'España',
    'name_it' => 'Spagna',
    'sort_order' => 80,
  ),
  8 => 
  array (
    'code' => 'IT',
    'name_nl' => 'Italië',
    'name_en' => 'Italy',
    'name_fr' => 'Italie',
    'name_de' => 'Italien',
    'name_es' => 'Italia',
    'name_it' => 'Italia',
    'sort_order' => 90,
  ),
  9 => 
  array (
    'code' => 'PT',
    'name_nl' => 'Portugal',
    'name_en' => 'Portugal',
    'name_fr' => 'Portugal',
    'name_de' => 'Portugal',
    'name_es' => 'Portugal',
    'name_it' => 'Portogallo',
    'sort_order' => 100,
  ),
  10 => 
  array (
    'code' => 'CH',
    'name_nl' => 'Zwitserland',
    'name_en' => 'Switzerland',
    'name_fr' => 'Suisse',
    'name_de' => 'Schweiz',
    'name_es' => 'Suiza',
    'name_it' => 'Svizzera',
    'sort_order' => 110,
  ),
  11 => 
  array (
    'code' => 'AT',
    'name_nl' => 'Oostenrijk',
    'name_en' => 'Austria',
    'name_fr' => 'Autriche',
    'name_de' => 'Österreich',
    'name_es' => 'Austria',
    'name_it' => 'Austria',
    'sort_order' => 120,
  ),
  12 => 
  array (
    'code' => 'PL',
    'name_nl' => 'Polen',
    'name_en' => 'Poland',
    'name_fr' => 'Pologne',
    'name_de' => 'Polen',
    'name_es' => 'Polonia',
    'name_it' => 'Polonia',
    'sort_order' => 130,
  ),
  13 => 
  array (
    'code' => 'CZ',
    'name_nl' => 'Tsjechië',
    'name_en' => 'Czech Republic',
    'name_fr' => 'République tchèque',
    'name_de' => 'Tschechien',
    'name_es' => 'República Checa',
    'name_it' => 'Repubblica Ceca',
    'sort_order' => 140,
  ),
  14 => 
  array (
    'code' => 'SK',
    'name_nl' => 'Slowakije',
    'name_en' => 'Slovakia',
    'name_fr' => 'Slovaquie',
    'name_de' => 'Slowakei',
    'name_es' => 'Eslovaquia',
    'name_it' => 'Slovacchia',
    'sort_order' => 150,
  ),
  15 => 
  array (
    'code' => 'HU',
    'name_nl' => 'Hongarije',
    'name_en' => 'Hungary',
    'name_fr' => 'Hongrie',
    'name_de' => 'Ungarn',
    'name_es' => 'Hungría',
    'name_it' => 'Ungheria',
    'sort_order' => 160,
  ),
  16 => 
  array (
    'code' => 'RO',
    'name_nl' => 'Roemenië',
    'name_en' => 'Romania',
    'name_fr' => 'Roumanie',
    'name_de' => 'Rumänien',
    'name_es' => 'Rumanía',
    'name_it' => 'Romania',
    'sort_order' => 170,
  ),
  17 => 
  array (
    'code' => 'BG',
    'name_nl' => 'Bulgarije',
    'name_en' => 'Bulgaria',
    'name_fr' => 'Bulgarie',
    'name_de' => 'Bulgarien',
    'name_es' => 'Bulgaria',
    'name_it' => 'Bulgaria',
    'sort_order' => 180,
  ),
  18 => 
  array (
    'code' => 'HR',
    'name_nl' => 'Kroatië',
    'name_en' => 'Croatia',
    'name_fr' => 'Croatie',
    'name_de' => 'Kroatien',
    'name_es' => 'Croacia',
    'name_it' => 'Croazia',
    'sort_order' => 190,
  ),
  19 => 
  array (
    'code' => 'SI',
    'name_nl' => 'Slovenië',
    'name_en' => 'Slovenia',
    'name_fr' => 'Slovénie',
    'name_de' => 'Slowenien',
    'name_es' => 'Eslovenia',
    'name_it' => 'Slovenia',
    'sort_order' => 200,
  ),
  20 => 
  array (
    'code' => 'US',
    'name_nl' => 'Verenigde Staten',
    'name_en' => 'United States',
    'name_fr' => 'États-Unis',
    'name_de' => 'Vereinigte Staaten',
    'name_es' => 'Estados Unidos',
    'name_it' => 'Stati Uniti',
    'sort_order' => 210,
  ),
  21 => 
  array (
    'code' => 'CA',
    'name_nl' => 'Canada',
    'name_en' => 'Canada',
    'name_fr' => 'Canada',
    'name_de' => 'Kanada',
    'name_es' => 'Canadá',
    'name_it' => 'Canada',
    'sort_order' => 220,
  ),
  22 => 
  array (
    'code' => 'MA',
    'name_nl' => 'Marokko',
    'name_en' => 'Morocco',
    'name_fr' => 'Maroc',
    'name_de' => 'Marokko',
    'name_es' => 'Marruecos',
    'name_it' => 'Marocco',
    'sort_order' => 230,
  ),
  23 => 
  array (
    'code' => 'TR',
    'name_nl' => 'Turkije',
    'name_en' => 'Turkey',
    'name_fr' => 'Turquie',
    'name_de' => 'Türkei',
    'name_es' => 'Turquía',
    'name_it' => 'Turchia',
    'sort_order' => 240,
  ),
  24 => 
  array (
    'code' => 'UA',
    'name_nl' => 'Oekraïne',
    'name_en' => 'Ukraine',
    'name_fr' => 'Ukraine',
    'name_de' => 'Ukraine',
    'name_es' => 'Ucrania',
    'name_it' => 'Ucraina',
    'sort_order' => 250,
  ),
  25 => 
  array (
    'code' => 'RS',
    'name_nl' => 'Servië',
    'name_en' => 'Serbia',
    'name_fr' => 'Serbie',
    'name_de' => 'Serbien',
    'name_es' => 'Serbia',
    'name_it' => 'Serbia',
    'sort_order' => 260,
  ),
  26 => 
  array (
    'code' => 'BA',
    'name_nl' => 'Bosnië en Herzegovina',
    'name_en' => 'Bosnia and Herzegovina',
    'name_fr' => 'Bosnie-Herzégovine',
    'name_de' => 'Bosnien und Herzegowina',
    'name_es' => 'Bosnia y Herzegovina',
    'name_it' => 'Bosnia ed Erzegovina',
    'sort_order' => 270,
  ),
  27 => 
  array (
    'code' => 'ME',
    'name_nl' => 'Montenegro',
    'name_en' => 'Montenegro',
    'name_fr' => 'Monténégro',
    'name_de' => 'Montenegro',
    'name_es' => 'Montenegro',
    'name_it' => 'Montenegro',
    'sort_order' => 280,
  ),
  28 => 
  array (
    'code' => 'MK',
    'name_nl' => 'Noord-Macedonië',
    'name_en' => 'North Macedonia',
    'name_fr' => 'Macédoine du Nord',
    'name_de' => 'Nordmazedonien',
    'name_es' => 'Macedonia del Norte',
    'name_it' => 'Macedonia del Nord',
    'sort_order' => 290,
  ),
  29 => 
  array (
    'code' => 'AL',
    'name_nl' => 'Albanië',
    'name_en' => 'Albania',
    'name_fr' => 'Albanie',
    'name_de' => 'Albanien',
    'name_es' => 'Albania',
    'name_it' => 'Albania',
    'sort_order' => 300,
  ),
);
